### ISSUE TITLE
[FE] Change domain model

### ISSUE THREAD

**Issue by Swop4a** [Swop4a/ssu-java-practice#14]

**Comment by Swop4a** [comment]
[
	{
		"id": 1,
		"title": "Private garage",
		"host": "Vasya Pupkin",
		"location": "Moscow, Kutuzovsky avenue 32",
		"cars": [
			{
				"id": 1,
				"make": "BMW",
				"model": "M3",
				"color": "Red",
				"creationDay": "2015-08-30",
				"mileage": 20000,
				"running": false
			},
			{
				"id": 2,
				"make": "Audi",
				"model": "A4",
				"color": "White",
				"creationDay": "2015-02-14",
				"mileage": 25000,
				"running": false
			},
			{
				"id": 3,
				"make": "Ford",
				"model": "Focus",
				"color": "Red",
				"creationDay": "2016-09-22",
				"mileage": 10000,
				"running": true
			}
		],
		"currentLoad": 3
	},
	{
		"id": 2,
		"title": "Mall parking",
		"host": "Roman Abramovich",
		"location": "Saratov, Astrahansky street 20",
		"cars": [],
		"currentLoad": 0
	},
	{
		"id": 3,
		"title": "Public parking",
		"host": "Public",
		"location": "Moscow, Sh. Entuziastov",
		"cars": [],
		"currentLoad": 0
	}
]

**Comment by Swop4a** [comment]
@pyxarez, pay attention:
1. currentLoad is not editable field. It is defined cars == null ? 0 : cars.size()
2. Could you please to add some date-picker for choosing date on add form

**Comment by pyxarez** [comment]
@Swop4a, affirmative, brother
